### PR TITLE
Upgrading Zit

### PR DESCRIPTION
**Pull request by dlundgren**
Thanks for Zit! 

I've been using it for years now, and recently performed some upgrades to it.

- Switched to PSR-11
- Auto-wiring
- Switch to Github actions
  - Supporting PHP 7.2+
  - I have this set up for coveralls reporting

### CODE REVIEW

**Comment by inxilpro** [comment]
Wow! Sorry I missed this. Obviously I haven't paid much attention to this project in a while. Would you prefer to just take the project over? I've moved to Laravel and haven't used Zit in a long time…

**Comment by dlundgren** [comment]
I know what it's like to lose track of a project! 

I can take on the project, as I'll be using it on a legacy project in to the foreseeable future.

**Comment by inxilpro** [comment]
Why don't you publish your version on packagist and send me the name. I'll tag one more release that marks this package deprecated and suggests your version, and archive this repo.

**Comment by dlundgren** [comment]
I've published `syberisle/zit` on packagist and tagged it as 3.0.1 with the `replace` set in composer.json.

**Comment by inxilpro** [comment]
Cool. I just updated the readme and marked the package as abandoned.

**Pull request closed without merging**
